### PR TITLE
Now Playing View

### PR DESCRIPTION
**Pull request by Dahlgren**
A rough Now Playing View. Please give it a try and leave feedback on what needs to be done before merging.

### CODE REVIEW

**Comment by sregg** [comment]
Thanks Dahlgren!

I think the only thing missing now is having the controls in the now playing screen (/ album details / playlist details).

I'm fighting right now with Google to appeal for the app suspension. I'll have a look at the now playing when that's done.

**Comment by Dahlgren** [comment]
I'll see if I can improve on it a bit. Playlist should keep current items and just change the song upon selection at least :P. I'll have a look at the buttons, something similar to Google Music should be doable.

**Comment by Dahlgren** [comment]
I guess it's time to have a look at this again since the app is back on the Play Store

**Comment by sregg** [comment]
@Dahlgren did you have time to have a look at this?

**Pull request merged**
